Import("env")

from pathlib import Path


def to_c_string_literal(value: str) -> str:
    """Convert text into a valid C string literal."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'

project_dir = Path(env["PROJECT_DIR"])
dotenv_path = project_dir / ".env"

if not dotenv_path.exists():
    raise RuntimeError(".env file not found. Create it from .env.example")

required_keys = ["WIFI_SSID", "WIFI_PASSWORD", "API_URL"]
values = {}

for raw_line in dotenv_path.read_text(encoding="utf-8").splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#"):
        continue
    if "=" not in line:
        continue

    key, value = line.split("=", 1)
    key = key.strip()
    value = value.strip()

    if value and len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
        value = value[1:-1]

    values[key] = value

missing = [k for k in required_keys if not values.get(k)]
if missing:
    raise RuntimeError("Missing required keys in .env: " + ", ".join(missing))

include_dir = project_dir / "include"
header_path = include_dir / "env_config.h"
include_dir.mkdir(parents=True, exist_ok=True)

header_lines = [
    "#pragma once",
    "",
    "// Auto-generated by scripts/load_dotenv.py from .env",
]

for key in required_keys:
    header_lines.append(f"#define {key} {to_c_string_literal(values[key])}")

header_content = "\n".join(header_lines) + "\n"
header_path.write_text(header_content, encoding="utf-8")
