#pragma once

enum FetchError {
  FETCH_OK = 0,
  ERROR_WIFI_CONNECT = 1,
  ERROR_WIFI_NOT_CONNECTED = 2,
  ERROR_HTTPS_INIT = 3,
  ERROR_SERVER_NO_RESPONSE = 4,
  ERROR_HTTP_STATUS = 5,
  ERROR_JSON_PARSE = 6,
  ERROR_SUBSCRIBERS_MISSING = 7,
  ERROR_SUBSCRIBERS_INVALID_TYPE = 8
};
